version: "3.9"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_app
    environment:
      VUE_APP_API_URL: "http://api:8081/api/"
    ports:
      - "8080:80"
    networks:
      - minha_rede_global

    restart: always

networks:
  minha_rede_global:
    external: true
